config/routes.rb
Blog::Application.routes.draw do

  devise_for :users
  root "welcome#index" 

  resources :tasks do
    post 'vote' => 'votes#create'
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/task.rb
class Task < ActiveRecord::Base

	has_many :comments

	has_many :votes

	validates :title, presence: true,
				length: { minimum: 5 }

  def votes_total
  	return nil if (upvotes + downvotes).empty?
  	upvotes.size - downvotes.size
  end

private

   def upvotes
   	 votes.up
   end

   def downvotes
   	 votes.down
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  
  belongs_to :task

  scope :up, -> { where(direction: 'up') }
  scope :down, -> { where(direction: 'down')}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :authenticate_user!

  def create
    @task = Task.find(params[:task_id])	
    @comment = @task.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to task_path(@task)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_action :authenticate_user!

	def index
	  @tasks = Task.all
	end

	def new 
	  @task = Task.new
	end

	def create 

	  @task = Task.create(params[:task].permit(:title, :description, :owner))	
	
	  if @task.save
	  	redirect_to @task
	  else
	  	render 'new'
	  end
	end

	def show
	  @task = Task.find(params[:id])	
	end

	def edit
	  @task = Task.find(params[:id])
	end

	def update

		@task = Task.find(params[:id])

		if @task.update(params[:task].permit(:title, :description, :owner))
	    redirect_to @task
	  else
	    render 'edit'
	  end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController 

before_action :authenticate_user!

  def create
    @task = Task.find(params[:task_id])
    @task.votes.create(direction: params[:direction])
  	# redirect_to '/tasks'

  	render json: { id: @task.id, votes: @task.votes_total }
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
<%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
<%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_for ([@task, @task.comments.build]) do |f| %>

<p>
  <%= f.label :commenter %>
  <%= f.text_field :commenter %>
</p>

<p>
  <%= f.label :Comment %>
  <%= f.text_field :body %>
</p>

<%= f.submit %>

<% end %>

app/views/comments/new.html.erb
<%= form_for ([@task, @task.comments.build]) do |f| %>

<p>
  <%= f.label :commenter %>
  <%= f.text_field :commenter %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_field :body %>
</p>

<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>


</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<%# form_for knows whether to 'update' or 'create' %>

<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited
      this task from being saved:</h2>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :description %><br>
<%= f.text_field :description %>
</p>

<p>
<%= f.label :owner %><br>
<%= f.text_field :owner %>
</p>

<%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1> Edit task:</h1>

<p>
<strong>Task title<strong>
<%= @task.title %>
</p>


<p>
  <strong>Task description</strong>
  <%= @task.description %>
</p>


<p>
  <strong>Owner:</strong>
  <%= @task.owner %>
</p>

<%= render "form" %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>List of current tasks:</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Owner</th>
    <th>Priority votes</th>
    <th>Comments count</th>
  </tr>
 
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.owner %></td>
      <td class='votes-count' data-id="<%= task.id %>"><%= task.votes_total %></td>
      <td><%= task.comments.count %></td>
      <td><%= link_to 'Show', task %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
      <td><%= button_to '⬆', task_vote_path(task, direction: "up", format: :json), remote: true %></td>
      <td><%= button_to '⬇', task_vote_path(task, direction: "down", format: :json), remote: true %></td>
    </tr>
    <%# task.votes.inspect %>
  <% end %>
</table>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1> New post </h1>

<%= render 'form' %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1> Your task: </h1>
<%= link_to 'My tasks', tasks_path %>
<%= link_to 'Edit', edit_task_path(@task) %>
<p>
<strong>Task title</strong>
<%= @task.title %>

<p>
  <strong>Task description</strong>
  <%= @task.description %>
</p>


<p>
  <strong>Owner:</strong>
  <%= @task.owner %>
</p>

<h2>Comments posted to this task: </h2>
<% @task.comments.each do |comment| %>

<%= render @task.comments %>

<% end %>

<br>

<h2> Add comment: <h2>

<%= render "comments/form" %>

<br>


<a href="#" onclick="this.style.backgroundColor='#0099000'">Paint it red</a>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<p>Not a member?  Not only are you a dick, but go on sign up:</p>

<%= link_to "Sign up", new_user_registration_path %>